# Generated by Django 2.2.8 on 2020-05-29 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': '小说类型',
                'verbose_name_plural': '小说类型',
                'db_table': 't_brand',
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='小说名')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('icon', models.ImageField(upload_to='icon', verbose_name='图标')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('status', models.IntegerField(choices=[[0, '连载中'], [1, '以完结']], default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='novels', to='novel.Brand')),
            ],
            options={
                'verbose_name': '小说主体',
                'verbose_name_plural': '小说主体',
                'db_table': 't_novel',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='章节标题')),
                ('content', models.FileField(upload_to='content', verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chapters', to='novel.Novel')),
            ],
            options={
                'verbose_name': '小说章节',
                'verbose_name_plural': '小说章节',
                'db_table': 't_chapter',
            },
        ),
    ]
