# Generated by Django 2.2.8 on 2020-05-10 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='novels', to='novel.Brand'),
        ),
    ]
